# Generated by Django 5.0.6 on 2024-06-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], default='GET', max_length=10)),
                ('type', models.CharField(choices=[('USER', 'USER'), ('PRODUCT', 'PRODUCT')], default='USER', max_length=10)),
                ('url', models.URLField()),
                ('response', models.JSONField(blank=True, null=True)),
                ('request', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
